CREATE DATABASE IF NOT EXISTS crud_demo;

USE crud_demo;

CREATE TABLE IF NOT EXISTS users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role  VARCHAR(50) DEFAULT  'User'
);